// src/lib/components/layout/Navbar.svelte
<script>
	import logo from "$lib/assets/logo.png";
</script>

<nav class="navbar navbar-expand-lg bg-primary sticky-top" data-bs-theme="dark">
	<div class="container-fluid">
		<div class="d-flex align-items-center gap-2">
			<img src={logo} alt="Logo" height="25rem" />
			<h5 class="text-white mb-0 me-3"><strong>Barbod Habibi</strong></h5>
		</div>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarColor01"
			aria-controls="navbarColor01"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarColor01">
			<ul class="navbar-nav me-auto">
				<li class="nav-item">
					<a class="nav-link" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/about">About Me</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/experience">Work Experience</a>
				</li>
				<li>
					<a class="nav-link" href="/skills">Skills</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/projects">Projects</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/resume.pdf" target="_blank" rel="noopener noreferrer">Resume</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

// features/navigation/components/Navbar.tsx
"use client";

import Link from "next/link";
import Image from "next/image";
import { navbarConfig } from "../navigation.constants";
import { TNavItem } from "../navigation.types";

const Navbar = () => {
  return (
    <nav className="w-full bg-white shadow-md">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          {/* Left: Logo + Title */}
          <div className="flex items-center space-x-3">
            <Link href="/" className="flex items-center space-x-2">
              {/* <Image src="/logo.png" alt="Site Logo" width={32} height={32} className="rounded" /> */}
              <span className="text-xl font-semibold text-gray-900">My Website</span>
            </Link>
          </div>

          {/* Right: Nav Links */}
          <div className="flex space-x-6">
            {navbarConfig.map((item: TNavItem) =>
              item.external ? (
                <a
                  key={item.id}
                  href={item.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-gray-700 hover:text-blue-500 transition-colors"
                >
                  {item.label}
                </a>
              ) : (
                <Link key={item.id} href={item.href} className="text-gray-700 hover:text-blue-500 transition-colors">
                  {item.label}
                </Link>
              ),
            )}
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
